### ISSUE TITLE
Page break with long tables not working

### ISSUE THREAD

**Issue by MartinHL** [JAEarly/latextable#1]
If I have long tables the page break does not work. I checked the web and found out that it does not work within a table environment because such an environment is unbreakable. 
Did I miss something or are long tables that spwan over more than one page not supported?

**Comment by JAEarly** [comment]
Thanks for logging this issue.

Can you provide some example code that demonstrates the problem please?

**Comment by MartinHL** [comment]
I created a test script see here: [test.txt](https://github.com/JAEarly/latextable/files/6101588/test.txt)
It creates a long table that does not fit onto one page. I would like to have a page break but it just writes over the footer beyond the end of the page. See here: [latex.txt](https://github.com/JAEarly/latextable/files/6101609/latex.txt)
I found [this article](https://stackoverflow.com/questions/26976703/latex-pagebreak-into-a-table) where it is stated the following:

> In order to have a longtable break across the page boundary, you need to place it on its own and not inside a floating table environment; the latter is unbreakable.

I'm not an expert in Latex, so if I'm doing something wrong I'd appreciate a hint how I can manage page breaks with long tables.

**Comment by JAEarly** [comment]
Apologies for the slow reply on this.

This issue is dependent on how the Latex output is rendered in the document. Determining if the table will be split across two pages is dependent on the table position, font size etc., so is not something that can be dealt with by this library. As such, this is will be closed without further work.
