### ISSUE TITLE
Table positioning

### ISSUE THREAD

**Issue by chriswales95** [JAEarly/latextable#2]
Hi,

is there any functionality to allow for positioning tables?

e.g. 

\begin{table}[h]
	\begin{center}
        ...

**Comment by JAEarly** [comment]
Hi,

Thanks for the question.

Currently there is not, as positioning tables like that doesn't really have a direct equivalent in texttable AFAIK.
If you'd like to submit a PR adding the feature, I'd be more than happy to take a look.
I am planning on putting together a set of new features for a future release - this could possibly be one of them.

Joe

**Comment by chriswales95** [comment]
Hi Joe,

that's what I thought. I had a quick look at the code and didn't see anything. Wanted to be sure.

It would be a really nice feature to have. Table positioning in Latex docs is something I frequently have to fiddle with as I'm sure others do too. I was very excited to come across this project and this is the only pain point I've come across.

I'll happily see if I can hack something out. I was going to create a workaround in the meantime anyway. I'll take a look later on and will open a pull request when I have something :).

Chris

**Comment by PhilW92** [comment]
Interestingly, I ran into the same problem two days ago.
I found a good solution by adding an optional parameter to the 
`texttable.draw()`
method.

I created a pull request: #3 

Cheers, Phil

**Comment by chriswales95** [comment]
@PhilW92 That's pretty much exactly what I had envisioned and partly coded locally as well but hadn't finished off due to other commitments. Would be a good feature to get in!

**Comment by JAEarly** [comment]
Core content completed with #3. Follow up tests and examples required.
