### ISSUE TITLE
Multicolumns support?

### ISSUE THREAD

**Issue by michaeldorner** [JAEarly/latextable#9]
Thanks for your great work. I wonder if and how multi-columns are doable?

**Comment by JAEarly** [comment]
Currently there is no support for multi-columns.
Please could you describe in more detail (preferably with examples) the features you would like and I can see about adding them.

**Comment by JAEarly** [comment]
As of ef7d096 and v1.0.0, I've added support for a multicolumn header row (above the normal header).
 As such, I'm closing this issue.

I hope that is what you're after.
If not, please re-open the issue or make a new one.

**Comment by michaeldorner** [comment]
You’re wonderful. Thanks for your effort!!!
